server:
  port: 8086
  tomcat:
    accesslog:
      enabled: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.format_sql: true

  datasource:
    #    url: jdbc:postgresql://localhost:5432/shoe_store_v2
#    url: jdbc:postgresql://dpg-cssc2uogph6c73947tmg-a.oregon-postgres.render.com:5432/shoe_fast
    url: jdbc:postgresql://dpg-cssc2uogph6c73947tmg-a/shoe_fast
    username: user_phuc
    #    password: 09122002
    password: Z1rzC30X31GMujuOTbyIWatN2uDF1Lca
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  mail:
    host: smtp.gmail.com
    port: 587
    username: pphuc9122002@gmail.com
    password: efxxykccrzktdmmv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true